package qt6

import (
	"unsafe"
)

// Source: libmiqt.h
type (
	Const_char = int8
)

type (
	Miqt_string struct {
		Len  uintptr
		Data *int8
	} // libmiqt.h:15 -> miqt_string
	Miqt_array struct {
		Len  uintptr
		Data unsafe.Pointer
	} // libmiqt.h:20 -> miqt_array
	Miqt_map struct {
		Len    uintptr
		Keys   unsafe.Pointer
		Values unsafe.Pointer
	} // libmiqt.h:25 -> miqt_map
	QWidget                          struct{} // sync_stubs.h:4 -> QWidget
	QAbstractEventDispatcher         struct{} // gen_cabi_QtCore.h:8 -> QAbstractEventDispatcher
	QAbstractItemModel               struct{} // gen_cabi_QtCore.h:9 -> QAbstractItemModel
	QAbstractNativeEventFilter       struct{} // gen_cabi_QtCore.h:10 -> QAbstractNativeEventFilter
	QAbstractProxyModel              struct{} // gen_cabi_QtCore.h:11 -> QAbstractProxyModel
	QAtomicInt                       struct{} // gen_cabi_QtCore.h:12 -> QAtomicInt
	QBasicTimer                      struct{} // gen_cabi_QtCore.h:13 -> QBasicTimer
	QBindingStorage                  struct{} // gen_cabi_QtCore.h:14 -> QBindingStorage
	QBitArray                        struct{} // gen_cabi_QtCore.h:15 -> QBitArray
	QBitRef                          struct{} // gen_cabi_QtCore.h:16 -> QBitRef
	QByteArray                       struct{} // gen_cabi_QtCore.h:17 -> QByteArray
	QCalendar                        struct{} // gen_cabi_QtCore.h:18 -> QCalendar
	QChar                            struct{} // gen_cabi_QtCore.h:19 -> QChar
	QChildEvent                      struct{} // gen_cabi_QtCore.h:20 -> QChildEvent
	QCoreApplication                 struct{} // gen_cabi_QtCore.h:21 -> QCoreApplication
	QDataStream                      struct{} // gen_cabi_QtCore.h:22 -> QDataStream
	QDate                            struct{} // gen_cabi_QtCore.h:23 -> QDate
	QDateTime                        struct{} // gen_cabi_QtCore.h:24 -> QDateTime
	QDeadlineTimer                   struct{} // gen_cabi_QtCore.h:25 -> QDeadlineTimer
	QDebug                           struct{} // gen_cabi_QtCore.h:26 -> QDebug
	QDir                             struct{} // gen_cabi_QtCore.h:27 -> QDir
	QEasingCurve                     struct{} // gen_cabi_QtCore.h:28 -> QEasingCurve
	QEvent                           struct{} // gen_cabi_QtCore.h:29 -> QEvent
	QEventLoop                       struct{} // gen_cabi_QtCore.h:30 -> QEventLoop
	QFileDevice                      struct{} // gen_cabi_QtCore.h:31 -> QFileDevice
	QFileInfo                        struct{} // gen_cabi_QtCore.h:32 -> QFileInfo
	QGenericArgument                 struct{} // gen_cabi_QtCore.h:33 -> QGenericArgument
	QGenericReturnArgument           struct{} // gen_cabi_QtCore.h:34 -> QGenericReturnArgument
	QIODevice                        struct{} // gen_cabi_QtCore.h:35 -> QIODevice
	QItemSelection                   struct{} // gen_cabi_QtCore.h:36 -> QItemSelection
	QItemSelectionModel              struct{} // gen_cabi_QtCore.h:37 -> QItemSelectionModel
	QItemSelectionRange              struct{} // gen_cabi_QtCore.h:38 -> QItemSelectionRange
	QJsonArray                       struct{} // gen_cabi_QtCore.h:39 -> QJsonArray
	QJsonDocument                    struct{} // gen_cabi_QtCore.h:40 -> QJsonDocument
	QJsonObject                      struct{} // gen_cabi_QtCore.h:41 -> QJsonObject
	QJsonParseError                  struct{} // gen_cabi_QtCore.h:42 -> QJsonParseError
	QJsonValue                       struct{} // gen_cabi_QtCore.h:43 -> QJsonValue
	QJsonValueConstRef               struct{} // gen_cabi_QtCore.h:44 -> QJsonValueConstRef
	QJsonValueRef                    struct{} // gen_cabi_QtCore.h:45 -> QJsonValueRef
	QKeyCombination                  struct{} // gen_cabi_QtCore.h:46 -> QKeyCombination
	QLine                            struct{} // gen_cabi_QtCore.h:47 -> QLine
	QLineF                           struct{} // gen_cabi_QtCore.h:48 -> QLineF
	QLocale                          struct{} // gen_cabi_QtCore.h:49 -> QLocale
	QMargins                         struct{} // gen_cabi_QtCore.h:50 -> QMargins
	QMarginsF                        struct{} // gen_cabi_QtCore.h:51 -> QMarginsF
	QMetaClassInfo                   struct{} // gen_cabi_QtCore.h:52 -> QMetaClassInfo
	QMetaEnum                        struct{} // gen_cabi_QtCore.h:53 -> QMetaEnum
	QMetaMethod                      struct{} // gen_cabi_QtCore.h:54 -> QMetaMethod
	QMetaObject                      struct{} // gen_cabi_QtCore.h:55 -> QMetaObject
	QMetaProperty                    struct{} // gen_cabi_QtCore.h:56 -> QMetaProperty
	QMetaType                        struct{} // gen_cabi_QtCore.h:57 -> QMetaType
	QMimeData                        struct{} // gen_cabi_QtCore.h:58 -> QMimeData
	QModelIndex                      struct{} // gen_cabi_QtCore.h:59 -> QModelIndex
	QModelRoleData                   struct{} // gen_cabi_QtCore.h:60 -> QModelRoleData
	QModelRoleDataSpan               struct{} // gen_cabi_QtCore.h:61 -> QModelRoleDataSpan
	QObject                          struct{} // gen_cabi_QtCore.h:62 -> QObject
	QPermission                      struct{} // gen_cabi_QtCore.h:63 -> QPermission
	QPersistentModelIndex            struct{} // gen_cabi_QtCore.h:64 -> QPersistentModelIndex
	QPoint                           struct{} // gen_cabi_QtCore.h:65 -> QPoint
	QPointF                          struct{} // gen_cabi_QtCore.h:66 -> QPointF
	QPropertyBindingError            struct{} // gen_cabi_QtCore.h:67 -> QPropertyBindingError
	QPropertyBindingSourceLocation   struct{} // gen_cabi_QtCore.h:68 -> QPropertyBindingSourceLocation
	QPropertyObserver                struct{} // gen_cabi_QtCore.h:69 -> QPropertyObserver
	QRect                            struct{} // gen_cabi_QtCore.h:70 -> QRect
	QRectF                           struct{} // gen_cabi_QtCore.h:71 -> QRectF
	QRegularExpression               struct{} // gen_cabi_QtCore.h:72 -> QRegularExpression
	QRegularExpressionMatch          struct{} // gen_cabi_QtCore.h:73 -> QRegularExpressionMatch
	QRegularExpressionMatchIterator  struct{} // gen_cabi_QtCore.h:74 -> QRegularExpressionMatchIterator
	QSize                            struct{} // gen_cabi_QtCore.h:75 -> QSize
	QSizeF                           struct{} // gen_cabi_QtCore.h:76 -> QSizeF
	QSocketNotifier                  struct{} // gen_cabi_QtCore.h:77 -> QSocketNotifier
	QString                          struct{} // gen_cabi_QtCore.h:78 -> QString
	QTextStream                      struct{} // gen_cabi_QtCore.h:79 -> QTextStream
	QTextStreamManipulator           struct{} // gen_cabi_QtCore.h:80 -> QTextStreamManipulator
	QThread                          struct{} // gen_cabi_QtCore.h:81 -> QThread
	QTime                            struct{} // gen_cabi_QtCore.h:82 -> QTime
	QTimeLine                        struct{} // gen_cabi_QtCore.h:83 -> QTimeLine
	QTimeZone                        struct{} // gen_cabi_QtCore.h:84 -> QTimeZone
	QTimer                           struct{} // gen_cabi_QtCore.h:85 -> QTimer
	QTimerEvent                      struct{} // gen_cabi_QtCore.h:86 -> QTimerEvent
	QTranslator                      struct{} // gen_cabi_QtCore.h:87 -> QTranslator
	QUntypedBindable                 struct{} // gen_cabi_QtCore.h:88 -> QUntypedBindable
	QUntypedPropertyBinding          struct{} // gen_cabi_QtCore.h:89 -> QUntypedPropertyBinding
	QUntypedPropertyData             struct{} // gen_cabi_QtCore.h:90 -> QUntypedPropertyData
	QUrl                             struct{} // gen_cabi_QtCore.h:91 -> QUrl
	QUrlQuery                        struct{} // gen_cabi_QtCore.h:92 -> QUrlQuery
	QUuid                            struct{} // gen_cabi_QtCore.h:93 -> QUuid
	QVariant                         struct{} // gen_cabi_QtCore.h:94 -> QVariant
	QAbstractFileIconProvider        struct{} // gen_cabi_QtGui.h:8 -> QAbstractFileIconProvider
	QAbstractTextDocumentLayout      struct{} // gen_cabi_QtGui.h:10 -> QAbstractTextDocumentLayout
	QAbstractUndoItem                struct{} // gen_cabi_QtGui.h:11 -> QAbstractUndoItem
	QAccessible                      struct{} // gen_cabi_QtGui.h:12 -> QAccessible
	QAccessibleActionInterface       struct{} // gen_cabi_QtGui.h:13 -> QAccessibleActionInterface
	QAccessibleAttributesInterface   struct{} // gen_cabi_QtGui.h:14 -> QAccessibleAttributesInterface
	QAccessibleEditableTextInterface struct{} // gen_cabi_QtGui.h:15 -> QAccessibleEditableTextInterface
	QAccessibleEvent                 struct{} // gen_cabi_QtGui.h:16 -> QAccessibleEvent
	QAccessibleHyperlinkInterface    struct{} // gen_cabi_QtGui.h:17 -> QAccessibleHyperlinkInterface
	QAccessibleImageInterface        struct{} // gen_cabi_QtGui.h:18 -> QAccessibleImageInterface
	QAccessibleInterface             struct{} // gen_cabi_QtGui.h:19 -> QAccessibleInterface
	QAccessibleSelectionInterface    struct{} // gen_cabi_QtGui.h:20 -> QAccessibleSelectionInterface
	QAccessibleTableCellInterface    struct{} // gen_cabi_QtGui.h:21 -> QAccessibleTableCellInterface
	QAccessibleTableInterface        struct{} // gen_cabi_QtGui.h:22 -> QAccessibleTableInterface
	QAccessibleTextInterface         struct{} // gen_cabi_QtGui.h:23 -> QAccessibleTextInterface
	QAccessibleValueInterface        struct{} // gen_cabi_QtGui.h:24 -> QAccessibleValueInterface
	QAction                          struct{} // gen_cabi_QtGui.h:25 -> QAction
	QActionEvent                     struct{} // gen_cabi_QtGui.h:26 -> QActionEvent
	QActionGroup                     struct{} // gen_cabi_QtGui.h:27 -> QActionGroup
	QBackingStore                    struct{} // gen_cabi_QtGui.h:28 -> QBackingStore
	QBitmap                          struct{} // gen_cabi_QtGui.h:29 -> QBitmap
	QBrush                           struct{} // gen_cabi_QtGui.h:30 -> QBrush
	QClipboard                       struct{} // gen_cabi_QtGui.h:33 -> QClipboard
	QCloseEvent                      struct{} // gen_cabi_QtGui.h:34 -> QCloseEvent
	QColor                           struct{} // gen_cabi_QtGui.h:35 -> QColor
	QColorSpace                      struct{} // gen_cabi_QtGui.h:36 -> QColorSpace
	QColorTransform                  struct{} // gen_cabi_QtGui.h:37 -> QColorTransform
	QContextMenuEvent                struct{} // gen_cabi_QtGui.h:38 -> QContextMenuEvent
	QCursor                          struct{} // gen_cabi_QtGui.h:40 -> QCursor
	QDrag                            struct{} // gen_cabi_QtGui.h:44 -> QDrag
	QDragEnterEvent                  struct{} // gen_cabi_QtGui.h:45 -> QDragEnterEvent
	QDragLeaveEvent                  struct{} // gen_cabi_QtGui.h:46 -> QDragLeaveEvent
	QDragMoveEvent                   struct{} // gen_cabi_QtGui.h:47 -> QDragMoveEvent
	QDropEvent                       struct{} // gen_cabi_QtGui.h:48 -> QDropEvent
	QEnterEvent                      struct{} // gen_cabi_QtGui.h:49 -> QEnterEvent
	QExposeEvent                     struct{} // gen_cabi_QtGui.h:51 -> QExposeEvent
	QFileSystemModel                 struct{} // gen_cabi_QtGui.h:53 -> QFileSystemModel
	QFocusEvent                      struct{} // gen_cabi_QtGui.h:54 -> QFocusEvent
	QFont                            struct{} // gen_cabi_QtGui.h:55 -> QFont
	QFontDatabase                    struct{} // gen_cabi_QtGui.h:56 -> QFontDatabase
	QFontInfo                        struct{} // gen_cabi_QtGui.h:57 -> QFontInfo
	QFontMetrics                     struct{} // gen_cabi_QtGui.h:58 -> QFontMetrics
	QFontMetricsF                    struct{} // gen_cabi_QtGui.h:59 -> QFontMetricsF
	QGlyphRun                        struct{} // gen_cabi_QtGui.h:60 -> QGlyphRun
	QGradient                        struct{} // gen_cabi_QtGui.h:61 -> QGradient
	QGuiApplication                  struct{} // gen_cabi_QtGui.h:62 -> QGuiApplication
	QHelpEvent                       struct{} // gen_cabi_QtGui.h:63 -> QHelpEvent
	QHideEvent                       struct{} // gen_cabi_QtGui.h:64 -> QHideEvent
	QHoverEvent                      struct{} // gen_cabi_QtGui.h:65 -> QHoverEvent
	QIcon                            struct{} // gen_cabi_QtGui.h:67 -> QIcon
	QIconEngine                      struct{} // gen_cabi_QtGui.h:68 -> QIconEngine
	QImage                           struct{} // gen_cabi_QtGui.h:69 -> QImage
	QImageReader                     struct{} // gen_cabi_QtGui.h:70 -> QImageReader
	QInputMethod                     struct{} // gen_cabi_QtGui.h:71 -> QInputMethod
	QInputMethodEvent                struct{} // gen_cabi_QtGui.h:72 -> QInputMethodEvent
	QKeyEvent                        struct{} // gen_cabi_QtGui.h:74 -> QKeyEvent
	QKeySequence                     struct{} // gen_cabi_QtGui.h:75 -> QKeySequence
	QMatrix4x4                       struct{} // gen_cabi_QtGui.h:81 -> QMatrix4x4
	QMouseEvent                      struct{} // gen_cabi_QtGui.h:87 -> QMouseEvent
	QMoveEvent                       struct{} // gen_cabi_QtGui.h:88 -> QMoveEvent
	QMovie                           struct{} // gen_cabi_QtGui.h:89 -> QMovie
	QPageLayout                      struct{} // gen_cabi_QtGui.h:91 -> QPageLayout
	QPageRanges                      struct{} // gen_cabi_QtGui.h:92 -> QPageRanges
	QPageSize                        struct{} // gen_cabi_QtGui.h:93 -> QPageSize
	QPagedPaintDevice                struct{} // gen_cabi_QtGui.h:94 -> QPagedPaintDevice
	QPaintDevice                     struct{} // gen_cabi_QtGui.h:95 -> QPaintDevice
	QPaintEngine                     struct{} // gen_cabi_QtGui.h:96 -> QPaintEngine
	QPaintEngineState                struct{} // gen_cabi_QtGui.h:97 -> QPaintEngineState
	QPaintEvent                      struct{} // gen_cabi_QtGui.h:98 -> QPaintEvent
	QPainter                         struct{} // gen_cabi_QtGui.h:99 -> QPainter
	QPainterPath                     struct{} // gen_cabi_QtGui.h:100 -> QPainterPath
	QPalette                         struct{} // gen_cabi_QtGui.h:101 -> QPalette
	QPen                             struct{} // gen_cabi_QtGui.h:102 -> QPen
	QPicture                         struct{} // gen_cabi_QtGui.h:103 -> QPicture
	QPixelFormat                     struct{} // gen_cabi_QtGui.h:104 -> QPixelFormat
	QPixmap                          struct{} // gen_cabi_QtGui.h:105 -> QPixmap
	QPointingDevice                  struct{} // gen_cabi_QtGui.h:108 -> QPointingDevice
	QPointingDeviceUniqueId          struct{} // gen_cabi_QtGui.h:109 -> QPointingDeviceUniqueId
	QPolygon                         struct{} // gen_cabi_QtGui.h:110 -> QPolygon
	QPolygonF                        struct{} // gen_cabi_QtGui.h:111 -> QPolygonF
	QQuaternion                      struct{} // gen_cabi_QtGui.h:112 -> QQuaternion
	QRegion                          struct{} // gen_cabi_QtGui.h:115 -> QRegion
	QResizeEvent                     struct{} // gen_cabi_QtGui.h:117 -> QResizeEvent
	QRgba64                          struct{} // gen_cabi_QtGui.h:118 -> QRgba64
	QScreen                          struct{} // gen_cabi_QtGui.h:119 -> QScreen
	QSessionManager                  struct{} // gen_cabi_QtGui.h:120 -> QSessionManager
	QShortcut                        struct{} // gen_cabi_QtGui.h:121 -> QShortcut
	QShowEvent                       struct{} // gen_cabi_QtGui.h:122 -> QShowEvent
	QStaticText                      struct{} // gen_cabi_QtGui.h:125 -> QStaticText
	QStyleHints                      struct{} // gen_cabi_QtGui.h:127 -> QStyleHints
	QSurfaceFormat                   struct{} // gen_cabi_QtGui.h:128 -> QSurfaceFormat
	QTabletEvent                     struct{} // gen_cabi_QtGui.h:129 -> QTabletEvent
	QTextBlock                       struct{} // gen_cabi_QtGui.h:130 -> QTextBlock
	QTextBlockFormat                 struct{} // gen_cabi_QtGui.h:131 -> QTextBlockFormat
	QTextBlockUserData               struct{} // gen_cabi_QtGui.h:132 -> QTextBlockUserData
	QTextCharFormat                  struct{} // gen_cabi_QtGui.h:133 -> QTextCharFormat
	QTextCursor                      struct{} // gen_cabi_QtGui.h:134 -> QTextCursor
	QTextDocument                    struct{} // gen_cabi_QtGui.h:135 -> QTextDocument
	QTextDocumentFragment            struct{} // gen_cabi_QtGui.h:136 -> QTextDocumentFragment
	QTextFormat                      struct{} // gen_cabi_QtGui.h:137 -> QTextFormat
	QTextFragment                    struct{} // gen_cabi_QtGui.h:138 -> QTextFragment
	QTextFrame                       struct{} // gen_cabi_QtGui.h:139 -> QTextFrame
	QTextFrameFormat                 struct{} // gen_cabi_QtGui.h:140 -> QTextFrameFormat
	QTextFrameLayoutData             struct{} // gen_cabi_QtGui.h:141 -> QTextFrameLayoutData
	QTextImageFormat                 struct{} // gen_cabi_QtGui.h:142 -> QTextImageFormat
	QTextInlineObject                struct{} // gen_cabi_QtGui.h:143 -> QTextInlineObject
	QTextItem                        struct{} // gen_cabi_QtGui.h:144 -> QTextItem
	QTextLayout                      struct{} // gen_cabi_QtGui.h:145 -> QTextLayout
	QTextLength                      struct{} // gen_cabi_QtGui.h:146 -> QTextLength
	QTextList                        struct{} // gen_cabi_QtGui.h:147 -> QTextList
	QTextListFormat                  struct{} // gen_cabi_QtGui.h:148 -> QTextListFormat
	QTextObject                      struct{} // gen_cabi_QtGui.h:149 -> QTextObject
	QTextObjectInterface             struct{} // gen_cabi_QtGui.h:150 -> QTextObjectInterface
	QTextOption                      struct{} // gen_cabi_QtGui.h:151 -> QTextOption
	QTextTable                       struct{} // gen_cabi_QtGui.h:152 -> QTextTable
	QTextTableCell                   struct{} // gen_cabi_QtGui.h:153 -> QTextTableCell
	QTextTableCellFormat             struct{} // gen_cabi_QtGui.h:154 -> QTextTableCellFormat
	QTextTableFormat                 struct{} // gen_cabi_QtGui.h:155 -> QTextTableFormat
	QTouchEvent                      struct{} // gen_cabi_QtGui.h:158 -> QTouchEvent
	QTransform                       struct{} // gen_cabi_QtGui.h:159 -> QTransform
	QUndoCommand                     struct{} // gen_cabi_QtGui.h:160 -> QUndoCommand
	QUndoGroup                       struct{} // gen_cabi_QtGui.h:161 -> QUndoGroup
	QUndoStack                       struct{} // gen_cabi_QtGui.h:162 -> QUndoStack
	QValidator                       struct{} // gen_cabi_QtGui.h:164 -> QValidator
	QVector2D                        struct{} // gen_cabi_QtGui.h:166 -> QVector2D
	QVector3D                        struct{} // gen_cabi_QtGui.h:167 -> QVector3D
	QVector4D                        struct{} // gen_cabi_QtGui.h:168 -> QVector4D
	QWheelEvent                      struct{} // gen_cabi_QtGui.h:169 -> QWheelEvent
	QWindow                          struct{} // gen_cabi_QtGui.h:170 -> QWindow
	QAbstractButton                  struct{} // gen_cabi_QtWidgets.h:8 -> QAbstractButton
	QAbstractGraphicsShapeItem       struct{} // gen_cabi_QtWidgets.h:10 -> QAbstractGraphicsShapeItem
	QAbstractItemDelegate            struct{} // gen_cabi_QtWidgets.h:11 -> QAbstractItemDelegate
	QAbstractItemView                struct{} // gen_cabi_QtWidgets.h:13 -> QAbstractItemView
	QAbstractScrollArea              struct{} // gen_cabi_QtWidgets.h:15 -> QAbstractScrollArea
	QAbstractSlider                  struct{} // gen_cabi_QtWidgets.h:16 -> QAbstractSlider
	QAbstractSpinBox                 struct{} // gen_cabi_QtWidgets.h:17 -> QAbstractSpinBox
	QAccessibleWidget                struct{} // gen_cabi_QtWidgets.h:22 -> QAccessibleWidget
	QAccessibleWidgetV2              struct{} // gen_cabi_QtWidgets.h:23 -> QAccessibleWidgetV2
	QApplication                     struct{} // gen_cabi_QtWidgets.h:26 -> QApplication
	QBoxLayout                       struct{} // gen_cabi_QtWidgets.h:29 -> QBoxLayout
	QButtonGroup                     struct{} // gen_cabi_QtWidgets.h:31 -> QButtonGroup
	QCalendarWidget                  struct{} // gen_cabi_QtWidgets.h:34 -> QCalendarWidget
	QCheckBox                        struct{} // gen_cabi_QtWidgets.h:35 -> QCheckBox
	QColorDialog                     struct{} // gen_cabi_QtWidgets.h:39 -> QColorDialog
	QColormap                        struct{} // gen_cabi_QtWidgets.h:40 -> QColormap
	QColumnView                      struct{} // gen_cabi_QtWidgets.h:41 -> QColumnView
	QComboBox                        struct{} // gen_cabi_QtWidgets.h:42 -> QComboBox
	QCommandLinkButton               struct{} // gen_cabi_QtWidgets.h:43 -> QCommandLinkButton
	QCommonStyle                     struct{} // gen_cabi_QtWidgets.h:44 -> QCommonStyle
	QCompleter                       struct{} // gen_cabi_QtWidgets.h:45 -> QCompleter
	QDataWidgetMapper                struct{} // gen_cabi_QtWidgets.h:50 -> QDataWidgetMapper
	QDateEdit                        struct{} // gen_cabi_QtWidgets.h:52 -> QDateEdit
	QDateTimeEdit                    struct{} // gen_cabi_QtWidgets.h:54 -> QDateTimeEdit
	QDial                            struct{} // gen_cabi_QtWidgets.h:55 -> QDial
	QDialog                          struct{} // gen_cabi_QtWidgets.h:56 -> QDialog
	QDialogButtonBox                 struct{} // gen_cabi_QtWidgets.h:57 -> QDialogButtonBox
	QDockWidget                      struct{} // gen_cabi_QtWidgets.h:59 -> QDockWidget
	QDoubleSpinBox                   struct{} // gen_cabi_QtWidgets.h:60 -> QDoubleSpinBox
	QErrorMessage                    struct{} // gen_cabi_QtWidgets.h:66 -> QErrorMessage
	QFileDialog                      struct{} // gen_cabi_QtWidgets.h:68 -> QFileDialog
	QFileIconProvider                struct{} // gen_cabi_QtWidgets.h:69 -> QFileIconProvider
	QFocusFrame                      struct{} // gen_cabi_QtWidgets.h:72 -> QFocusFrame
	QFontComboBox                    struct{} // gen_cabi_QtWidgets.h:74 -> QFontComboBox
	QFontDialog                      struct{} // gen_cabi_QtWidgets.h:75 -> QFontDialog
	QFormLayout                      struct{} // gen_cabi_QtWidgets.h:78 -> QFormLayout
	QFrame                           struct{} // gen_cabi_QtWidgets.h:79 -> QFrame
	QGesture                         struct{} // gen_cabi_QtWidgets.h:80 -> QGesture
	QGestureEvent                    struct{} // gen_cabi_QtWidgets.h:81 -> QGestureEvent
	QGestureRecognizer               struct{} // gen_cabi_QtWidgets.h:82 -> QGestureRecognizer
	QGraphicsAnchor                  struct{} // gen_cabi_QtWidgets.h:83 -> QGraphicsAnchor
	QGraphicsAnchorLayout            struct{} // gen_cabi_QtWidgets.h:84 -> QGraphicsAnchorLayout
	QGraphicsBlurEffect              struct{} // gen_cabi_QtWidgets.h:85 -> QGraphicsBlurEffect
	QGraphicsColorizeEffect          struct{} // gen_cabi_QtWidgets.h:86 -> QGraphicsColorizeEffect
	QGraphicsDropShadowEffect        struct{} // gen_cabi_QtWidgets.h:87 -> QGraphicsDropShadowEffect
	QGraphicsEffect                  struct{} // gen_cabi_QtWidgets.h:88 -> QGraphicsEffect
	QGraphicsEllipseItem             struct{} // gen_cabi_QtWidgets.h:89 -> QGraphicsEllipseItem
	QGraphicsGridLayout              struct{} // gen_cabi_QtWidgets.h:90 -> QGraphicsGridLayout
	QGraphicsItem                    struct{} // gen_cabi_QtWidgets.h:91 -> QGraphicsItem
	QGraphicsItemAnimation           struct{} // gen_cabi_QtWidgets.h:92 -> QGraphicsItemAnimation
	QGraphicsItemGroup               struct{} // gen_cabi_QtWidgets.h:93 -> QGraphicsItemGroup
	QGraphicsLayout                  struct{} // gen_cabi_QtWidgets.h:94 -> QGraphicsLayout
	QGraphicsLayoutItem              struct{} // gen_cabi_QtWidgets.h:95 -> QGraphicsLayoutItem
	QGraphicsLineItem                struct{} // gen_cabi_QtWidgets.h:96 -> QGraphicsLineItem
	QGraphicsLinearLayout            struct{} // gen_cabi_QtWidgets.h:97 -> QGraphicsLinearLayout
	QGraphicsObject                  struct{} // gen_cabi_QtWidgets.h:98 -> QGraphicsObject
	QGraphicsOpacityEffect           struct{} // gen_cabi_QtWidgets.h:99 -> QGraphicsOpacityEffect
	QGraphicsPathItem                struct{} // gen_cabi_QtWidgets.h:100 -> QGraphicsPathItem
	QGraphicsPixmapItem              struct{} // gen_cabi_QtWidgets.h:101 -> QGraphicsPixmapItem
	QGraphicsPolygonItem             struct{} // gen_cabi_QtWidgets.h:102 -> QGraphicsPolygonItem
	QGraphicsProxyWidget             struct{} // gen_cabi_QtWidgets.h:103 -> QGraphicsProxyWidget
	QGraphicsRectItem                struct{} // gen_cabi_QtWidgets.h:104 -> QGraphicsRectItem
	QGraphicsRotation                struct{} // gen_cabi_QtWidgets.h:105 -> QGraphicsRotation
	QGraphicsScale                   struct{} // gen_cabi_QtWidgets.h:106 -> QGraphicsScale
	QGraphicsScene                   struct{} // gen_cabi_QtWidgets.h:107 -> QGraphicsScene
	QGraphicsSceneContextMenuEvent   struct{} // gen_cabi_QtWidgets.h:108 -> QGraphicsSceneContextMenuEvent
	QGraphicsSceneDragDropEvent      struct{} // gen_cabi_QtWidgets.h:109 -> QGraphicsSceneDragDropEvent
	QGraphicsSceneEvent              struct{} // gen_cabi_QtWidgets.h:110 -> QGraphicsSceneEvent
	QGraphicsSceneHelpEvent          struct{} // gen_cabi_QtWidgets.h:111 -> QGraphicsSceneHelpEvent
	QGraphicsSceneHoverEvent         struct{} // gen_cabi_QtWidgets.h:112 -> QGraphicsSceneHoverEvent
	QGraphicsSceneMouseEvent         struct{} // gen_cabi_QtWidgets.h:113 -> QGraphicsSceneMouseEvent
	QGraphicsSceneMoveEvent          struct{} // gen_cabi_QtWidgets.h:114 -> QGraphicsSceneMoveEvent
	QGraphicsSceneResizeEvent        struct{} // gen_cabi_QtWidgets.h:115 -> QGraphicsSceneResizeEvent
	QGraphicsSceneWheelEvent         struct{} // gen_cabi_QtWidgets.h:116 -> QGraphicsSceneWheelEvent
	QGraphicsSimpleTextItem          struct{} // gen_cabi_QtWidgets.h:117 -> QGraphicsSimpleTextItem
	QGraphicsTextItem                struct{} // gen_cabi_QtWidgets.h:118 -> QGraphicsTextItem
	QGraphicsTransform               struct{} // gen_cabi_QtWidgets.h:119 -> QGraphicsTransform
	QGraphicsView                    struct{} // gen_cabi_QtWidgets.h:120 -> QGraphicsView
	QGraphicsWidget                  struct{} // gen_cabi_QtWidgets.h:121 -> QGraphicsWidget
	QGridLayout                      struct{} // gen_cabi_QtWidgets.h:122 -> QGridLayout
	QGroupBox                        struct{} // gen_cabi_QtWidgets.h:123 -> QGroupBox
	QHBoxLayout                      struct{} // gen_cabi_QtWidgets.h:125 -> QHBoxLayout
	QHeaderView                      struct{} // gen_cabi_QtWidgets.h:126 -> QHeaderView
	QInputDialog                     struct{} // gen_cabi_QtWidgets.h:131 -> QInputDialog
	QItemDelegate                    struct{} // gen_cabi_QtWidgets.h:133 -> QItemDelegate
	QItemEditorCreatorBase           struct{} // gen_cabi_QtWidgets.h:134 -> QItemEditorCreatorBase
	QItemEditorFactory               struct{} // gen_cabi_QtWidgets.h:135 -> QItemEditorFactory
	QKeySequenceEdit                 struct{} // gen_cabi_QtWidgets.h:141 -> QKeySequenceEdit
	QLCDNumber                       struct{} // gen_cabi_QtWidgets.h:142 -> QLCDNumber
	QLabel                           struct{} // gen_cabi_QtWidgets.h:143 -> QLabel
	QLayout                          struct{} // gen_cabi_QtWidgets.h:144 -> QLayout
	QLayoutItem                      struct{} // gen_cabi_QtWidgets.h:145 -> QLayoutItem
	QLineEdit                        struct{} // gen_cabi_QtWidgets.h:146 -> QLineEdit
	QListView                        struct{} // gen_cabi_QtWidgets.h:148 -> QListView
	QListWidget                      struct{} // gen_cabi_QtWidgets.h:149 -> QListWidget
	QListWidgetItem                  struct{} // gen_cabi_QtWidgets.h:150 -> QListWidgetItem
	QMainWindow                      struct{} // gen_cabi_QtWidgets.h:152 -> QMainWindow
	QMdiArea                         struct{} // gen_cabi_QtWidgets.h:156 -> QMdiArea
	QMdiSubWindow                    struct{} // gen_cabi_QtWidgets.h:157 -> QMdiSubWindow
	QMenu                            struct{} // gen_cabi_QtWidgets.h:158 -> QMenu
	QMenuBar                         struct{} // gen_cabi_QtWidgets.h:159 -> QMenuBar
	QMessageBox                      struct{} // gen_cabi_QtWidgets.h:160 -> QMessageBox
	QPanGesture                      struct{} // gen_cabi_QtWidgets.h:176 -> QPanGesture
	QPinchGesture                    struct{} // gen_cabi_QtWidgets.h:179 -> QPinchGesture
	QPlainTextDocumentLayout         struct{} // gen_cabi_QtWidgets.h:181 -> QPlainTextDocumentLayout
	QPlainTextEdit                   struct{} // gen_cabi_QtWidgets.h:182 -> QPlainTextEdit
	QProgressBar                     struct{} // gen_cabi_QtWidgets.h:185 -> QProgressBar
	QProgressDialog                  struct{} // gen_cabi_QtWidgets.h:186 -> QProgressDialog
	QProxyStyle                      struct{} // gen_cabi_QtWidgets.h:187 -> QProxyStyle
	QPushButton                      struct{} // gen_cabi_QtWidgets.h:188 -> QPushButton
	QRadioButton                     struct{} // gen_cabi_QtWidgets.h:189 -> QRadioButton
	QRhiCommandBuffer                struct{} // gen_cabi_QtWidgets.h:195 -> QRhiCommandBuffer
	QRhiRenderBuffer                 struct{} // gen_cabi_QtWidgets.h:196 -> QRhiRenderBuffer
	QRhiTexture                      struct{} // gen_cabi_QtWidgets.h:197 -> QRhiTexture
	QRhiWidget                       struct{} // gen_cabi_QtWidgets.h:198 -> QRhiWidget
	QRubberBand                      struct{} // gen_cabi_QtWidgets.h:199 -> QRubberBand
	QScrollArea                      struct{} // gen_cabi_QtWidgets.h:201 -> QScrollArea
	QScrollBar                       struct{} // gen_cabi_QtWidgets.h:202 -> QScrollBar
	QScroller                        struct{} // gen_cabi_QtWidgets.h:203 -> QScroller
	QScrollerProperties              struct{} // gen_cabi_QtWidgets.h:204 -> QScrollerProperties
	QSizeGrip                        struct{} // gen_cabi_QtWidgets.h:208 -> QSizeGrip
	QSizePolicy                      struct{} // gen_cabi_QtWidgets.h:209 -> QSizePolicy
	QSlider                          struct{} // gen_cabi_QtWidgets.h:210 -> QSlider
	QSpacerItem                      struct{} // gen_cabi_QtWidgets.h:211 -> QSpacerItem
	QSpinBox                         struct{} // gen_cabi_QtWidgets.h:212 -> QSpinBox
	QSplashScreen                    struct{} // gen_cabi_QtWidgets.h:213 -> QSplashScreen
	QSplitter                        struct{} // gen_cabi_QtWidgets.h:214 -> QSplitter
	QSplitterHandle                  struct{} // gen_cabi_QtWidgets.h:215 -> QSplitterHandle
	QStackedLayout                   struct{} // gen_cabi_QtWidgets.h:216 -> QStackedLayout
	QStackedWidget                   struct{} // gen_cabi_QtWidgets.h:217 -> QStackedWidget
	QStatusBar                       struct{} // gen_cabi_QtWidgets.h:218 -> QStatusBar
	QStyle                           struct{} // gen_cabi_QtWidgets.h:220 -> QStyle
	QStyleFactory                    struct{} // gen_cabi_QtWidgets.h:221 -> QStyleFactory
	QStyleHintReturn                 struct{} // gen_cabi_QtWidgets.h:222 -> QStyleHintReturn
	QStyleHintReturnMask             struct{} // gen_cabi_QtWidgets.h:223 -> QStyleHintReturnMask
	QStyleHintReturnVariant          struct{} // gen_cabi_QtWidgets.h:224 -> QStyleHintReturnVariant
	QStyleOption                     struct{} // gen_cabi_QtWidgets.h:225 -> QStyleOption
	QStyleOptionButton               struct{} // gen_cabi_QtWidgets.h:226 -> QStyleOptionButton
	QStyleOptionComboBox             struct{} // gen_cabi_QtWidgets.h:227 -> QStyleOptionComboBox
	QStyleOptionComplex              struct{} // gen_cabi_QtWidgets.h:228 -> QStyleOptionComplex
	QStyleOptionDockWidget           struct{} // gen_cabi_QtWidgets.h:229 -> QStyleOptionDockWidget
	QStyleOptionFocusRect            struct{} // gen_cabi_QtWidgets.h:230 -> QStyleOptionFocusRect
	QStyleOptionFrame                struct{} // gen_cabi_QtWidgets.h:231 -> QStyleOptionFrame
	QStyleOptionGraphicsItem         struct{} // gen_cabi_QtWidgets.h:232 -> QStyleOptionGraphicsItem
	QStyleOptionGroupBox             struct{} // gen_cabi_QtWidgets.h:233 -> QStyleOptionGroupBox
	QStyleOptionHeader               struct{} // gen_cabi_QtWidgets.h:234 -> QStyleOptionHeader
	QStyleOptionHeaderV2             struct{} // gen_cabi_QtWidgets.h:235 -> QStyleOptionHeaderV2
	QStyleOptionMenuItem             struct{} // gen_cabi_QtWidgets.h:236 -> QStyleOptionMenuItem
	QStyleOptionMenuItemV2           struct{} // gen_cabi_QtWidgets.h:237 -> QStyleOptionMenuItemV2
	QStyleOptionProgressBar          struct{} // gen_cabi_QtWidgets.h:238 -> QStyleOptionProgressBar
	QStyleOptionRubberBand           struct{} // gen_cabi_QtWidgets.h:239 -> QStyleOptionRubberBand
	QStyleOptionSizeGrip             struct{} // gen_cabi_QtWidgets.h:240 -> QStyleOptionSizeGrip
	QStyleOptionSlider               struct{} // gen_cabi_QtWidgets.h:241 -> QStyleOptionSlider
	QStyleOptionSpinBox              struct{} // gen_cabi_QtWidgets.h:242 -> QStyleOptionSpinBox
	QStyleOptionTab                  struct{} // gen_cabi_QtWidgets.h:243 -> QStyleOptionTab
	QStyleOptionTabBarBase           struct{} // gen_cabi_QtWidgets.h:244 -> QStyleOptionTabBarBase
	QStyleOptionTabWidgetFrame       struct{} // gen_cabi_QtWidgets.h:245 -> QStyleOptionTabWidgetFrame
	QStyleOptionTitleBar             struct{} // gen_cabi_QtWidgets.h:246 -> QStyleOptionTitleBar
	QStyleOptionToolBar              struct{} // gen_cabi_QtWidgets.h:247 -> QStyleOptionToolBar
	QStyleOptionToolBox              struct{} // gen_cabi_QtWidgets.h:248 -> QStyleOptionToolBox
	QStyleOptionToolButton           struct{} // gen_cabi_QtWidgets.h:249 -> QStyleOptionToolButton
	QStyleOptionViewItem             struct{} // gen_cabi_QtWidgets.h:250 -> QStyleOptionViewItem
	QStylePainter                    struct{} // gen_cabi_QtWidgets.h:251 -> QStylePainter
	QStylePlugin                     struct{} // gen_cabi_QtWidgets.h:252 -> QStylePlugin
	QStyledItemDelegate              struct{} // gen_cabi_QtWidgets.h:253 -> QStyledItemDelegate
	QSwipeGesture                    struct{} // gen_cabi_QtWidgets.h:254 -> QSwipeGesture
	QSystemTrayIcon                  struct{} // gen_cabi_QtWidgets.h:255 -> QSystemTrayIcon
	QTabBar                          struct{} // gen_cabi_QtWidgets.h:256 -> QTabBar
	QTabWidget                       struct{} // gen_cabi_QtWidgets.h:257 -> QTabWidget
	QTableView                       struct{} // gen_cabi_QtWidgets.h:258 -> QTableView
	QTableWidget                     struct{} // gen_cabi_QtWidgets.h:259 -> QTableWidget
	QTableWidgetItem                 struct{} // gen_cabi_QtWidgets.h:260 -> QTableWidgetItem
	QTableWidgetSelectionRange       struct{} // gen_cabi_QtWidgets.h:261 -> QTableWidgetSelectionRange
	QTapAndHoldGesture               struct{} // gen_cabi_QtWidgets.h:263 -> QTapAndHoldGesture
	QTapGesture                      struct{} // gen_cabi_QtWidgets.h:264 -> QTapGesture
	QTextBrowser                     struct{} // gen_cabi_QtWidgets.h:266 -> QTextBrowser
	QTextEdit                        struct{} // gen_cabi_QtWidgets.h:270 -> QTextEdit
	QTileRules                       struct{} // gen_cabi_QtWidgets.h:272 -> QTileRules
	QTimeEdit                        struct{} // gen_cabi_QtWidgets.h:274 -> QTimeEdit
	QToolBar                         struct{} // gen_cabi_QtWidgets.h:278 -> QToolBar
	QToolBox                         struct{} // gen_cabi_QtWidgets.h:279 -> QToolBox
	QToolButton                      struct{} // gen_cabi_QtWidgets.h:280 -> QToolButton
	QToolTip                         struct{} // gen_cabi_QtWidgets.h:281 -> QToolTip
	QTreeView                        struct{} // gen_cabi_QtWidgets.h:283 -> QTreeView
	QTreeWidget                      struct{} // gen_cabi_QtWidgets.h:284 -> QTreeWidget
	QTreeWidgetItem                  struct{} // gen_cabi_QtWidgets.h:285 -> QTreeWidgetItem
	QTreeWidgetItemIterator          struct{} // gen_cabi_QtWidgets.h:286 -> QTreeWidgetItemIterator
	QUndoView                        struct{} // gen_cabi_QtWidgets.h:289 -> QUndoView
	QVBoxLayout                      struct{} // gen_cabi_QtWidgets.h:291 -> QVBoxLayout
	QWhatsThis                       struct{} // gen_cabi_QtWidgets.h:295 -> QWhatsThis
	QWidgetAction                    struct{} // gen_cabi_QtWidgets.h:298 -> QWidgetAction
	QWidgetData                      struct{} // gen_cabi_QtWidgets.h:299 -> QWidgetData
	QWidgetItem                      struct{} // gen_cabi_QtWidgets.h:300 -> QWidgetItem
	QWidgetItemV2                    struct{} // gen_cabi_QtWidgets.h:301 -> QWidgetItemV2
	QWizard                          struct{} // gen_cabi_QtWidgets.h:303 -> QWizard
	QWizardPage                      struct{} // gen_cabi_QtWidgets.h:304 -> QWizardPage
)
